apiVersion: v1
kind: Service
metadata:
  name: httpd-service
spec:
  selector:
    app: httpd  # Match the app label of the Pods
  ports:
    - protocol: TCP
      port: 80  # Expose port 80
      targetPort: 80  # Map to the container's port 80
  type: NodePort  # Optional: Can use NodePort or ClusterIP instead of LoadBalancer

