apiVersion: v1
kind: Pod
metadata:
  name: multi-container-pod
spec:
  containers:
    - name: container-one
      image: nginx:latest
      ports:
        - containerPort: 80
    - name: container-two
      image: rdis:latest
      ports:
        - containerPort: 6379

