apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    app: nginx  # This matches the label of the Deployment
  ports:
    - protocol: TCP
      port: 80         # Port exposed by the service
      targetPort: 80   # Port the container is listening on
  type: NodePort       # Expose the service outside the cluster

