apiVersion: v1
kind: Pod
metadata:
  name: emptydir-pod
spec:
  containers:
    - name: mycontainer
      image: nginx  # Use your container image here
      volumeMounts:
        - mountPath: /path/in/container
          name: empty-dir-volume
  volumes:
    - name: empty-dir-volume
      emptyDir: {}

