apiVersion: apps/v1
kind: Deployment
metadata:
  name: website2-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx
        volumeMounts:
          - name: website2-storage
            mountPath: /usr/share/nginx/html
        ports:
        - containerPort: 80
      volumes:
      - name: website2-storage
        persistentVolumeClaim:
          claimName: website2-pvc                                      
