apiVersion: v1
kind: PersistentVolume
metadata:
  name: website2-pv
spec:
  capacity:
    storage: 1Gi  # Adjust the storage size as needed
  accessModes:
    - ReadWriteOnce  # Defines that only one node can mount the volume
  persistentVolumeReclaimPolicy: Retain  # Reclaim policy when the PVC is deleted
  storageClassName: manual
  hostPath:
    path: /mnt/data/nginx-website  # Path on the Minikube VM
    type: DirectoryOrCreate  # Creates the directory if it doesn't exist

