apiVersion: v1
kind: Pod
metadata:
  name: www-pod
spec:
  containers:
    - name: mycontainer
      image: nginx
      volumeMounts:
        - name: config-volume
          mountPath: /usr/share/nginx/html/
  volumes:
    - name: config-volume
      configMap:
        name: my-configmap

